Fix installation without websrv
aalaesar/install_nextcloud pull request #173
Opened 2022-12-24 14:22 UTC by bemyak

This PR fixes installation with `nextcloud_install_websrv: false` option. Currently, `php_install` always installs the webserver without taking the option into account.

2022-12-25 17:14 UTC, staticdev commented
@bemyak could you give a bit more context explaining what you changed? Did you test it also tour changed with ’nextcloud_install_websrv: true'?

2022-12-25 20:46 UTC, bemyak commented
> Could you give a bit more context explaining what you changed?

Sure. In general, I'm trying to make this role work with Caddy web server, which is installed as a separate role.

I've extracted the web server installation from `php-install.yml` into a separate file `websrv_install.yml`. This file is only applied when `nextcloud_install_websrv` is set to true.

Another minor change is the explicit installation of `php-fpm`. I believe currently it's installed as a web server dependency, but when there is none, it should be installed as part of `php-install`.

> Did you test it also your charges with `nextcloud_install_websrv: true`?

Nope, sorry :innocent:  
I messed up with the file extension; this is fixed now, so CI should pass (testes locally with molecule).

2022-12-25 21:14 UTC, bemyak commented
The last commit adds `php-bz2` module as the [Nextcloud docs](https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html) say that it's `recommended, required for extraction of apps`

2022-12-27 18:02 UTC, staticdev requested changes
Thanks again for your PR @bemyak I had some time to review it and has some minor findings.

2022-12-27 18:02 UTC, staticdev commented on tasks/websrv_install.yml
> +- name: "[INSTALL] - NGINX Required package is installed."
```suggestion
- name: "[INSTALL] - NGINX required package is installed."
```

2022-12-27 18:16 UTC, bemyak commented on tasks/php_install.yml
> +    - "php-fpm"
On which distro are you checking? On Ubuntu 22.04 it works without the version:
```
root@nextcloud:~# apt install php-fpm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php-fpm is already the newest version (2:8.1+92ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
```

But I will add it, no problem.

2022-12-27 20:35 UTC, wiktor2200 requested changes

2022-12-27 21:13 UTC, staticdev commented on tasks/php_install.yml
> +    - "php-fpm"
Debian 11

2022-12-27 21:23 UTC, staticdev commented on tasks/main.yml
> +- name: Install web server packages
@wiktor2200 oh, I missed that one!

2022-12-28 13:14 UTC, bemyak commented
Thanks for the review! The issues are addressed now.

2022-12-28 13:45 UTC, staticdev approved these changes

2022-12-28 13:46 UTC, staticdev commented
@wiktor2200 LGTM?

2022-12-28 15:09 UTC, wiktor2200 commented
Looks good now :)

śr., 28 gru 2022, 14:46 użytkownik staticdev ***@***.***>
napisał:

> @wiktor2200 <https://github.com/wiktor2200> LGTM?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/aalaesar/install_nextcloud/pull/173#issuecomment-1366664443>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHEPTUETZTAYSLVWXOTH3UTWPRACRANCNFSM6AAAAAATIPGKUI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-28 15:10 UTC, wiktor2200 commented
Looks good now :)

2022-12-28 15:11 UTC, wiktor2200 approved these changes

2022-12-28 15:40 UTC, merged