Relase 2.0 - change to an ansible collection
aalaesar/install_nextcloud pull request #206
Opened 2023-02-09 08:30 UTC by aalaesar

Preparing release
@staticdev can the release drafter manage all the changes here or should we edit it ? I noted that is has overwritten my comments on the draft release last time.

2023-02-09 09:11 UTC, staticdev commented
> Preparing release @staticdev can the release drafter manage all the changes here or should we edit it ? I noted that is has overwritten my comments on the draft release last time.

Release manager considers all PRs to main, except with tag `skip-changelog` as one change. In this case, makes sense to edit manually since it is a special case.

2023-02-09 21:23 UTC, aalaesar commented
> > Preparing release @staticdev can the release drafter manage all the changes here or should we edit it ? I noted that is has overwritten my comments on the draft release last time.
> 
> Release Drafter considers all PRs to main, except with tag `skip-changelog` as one change. In this case, makes sense to edit manually since it is a special case.

Ok but I have a doubt : last time I edited the release draft to add a comment that this was the last release as a role, but this comment is not in the 1.8.0 release.
unless someone removed it ?

2023-02-10 00:05 UTC, aalaesar commented
I expect troubles with galaxy when this PR is merged. 

I haven't found doc about converting a role into a collection for galaxy (and keeping stats)
could be a nice exp for when transferring to nextcloud (but it will have a larger exposure so good stats may not be that hard to get)

I didn't found doc about transferring a role in galaxy to an other organization either...

2023-02-10 08:15 UTC, staticdev commented
> I expect troubles with galaxy when this PR is merged.
> 
> I haven't found doc about converting a role into a collection for galaxy (and keeping stats) could be a nice exp for when transferring to nextcloud (but it will have a larger exposure so good stats may not be that hard to get)
> 
> I didn't found doc about transferring a role in galaxy to an other organization either...

@aalaesar I also had trouble with that. Probably there was a merge of PR after your edit and then Release-Drafter overwritten it. This is why currently I edit after the release to be 100% safe =p

2023-02-11 20:50 UTC, wiktor2200 requested changes
I've taken a look on whole PR. I was able to verify all file moves, yml and other. I've not verified python plugins (I think nothing has changed since last review by @staticdev).

2023-02-11 21:01 UTC, wiktor2200 commented on README.md
> +aalaesar.nextcloud.install_nextcloud|Install and configure an Nextcloud instance for a Debian/Ubuntu server - formerly `aalaesar.install_nextcloud`
Maybe it's worth adding link to role here:
```suggestion
[aalaesar.nextcloud.install_nextcloud](roles/install_nextcloud)|Install and configure an Nextcloud instance for a Debian/Ubuntu server - formerly `aalaesar.install_nextcloud`
```

2023-02-11 23:29 UTC, aalaesar commented on galaxy.yml
> +dependencies: {}
Hmm.
I'm cautious with how ansible deal with dependencies declared in the meta.
As for roles, it implies that ansible run the roles declared as dependency first
I'll look at Galaxy doc first. And will do some test install and run.
Could be worth a PR.

2023-02-11 23:35 UTC, wiktor2200 commented on galaxy.yml
> +dependencies: {}
Sure, makes sense. It would be bad to run whole external role with default values accidentally, without any flow control :)

2023-02-12 21:27 UTC, aalaesar commented on galaxy.yml
> +dependencies: {}
I've check ove the [galaxy doc](https://docs.ansible.com/ansible/devel/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta)
looks like this field is only dedicated for collections, not roles
SO they may be an issue when installing the collection with the ansible-galaxy install command that will not pull the php_repository role from geerlinguy

2023-02-12 21:36 UTC, aalaesar commented on galaxy.yml
> +dependencies: {}
found https://github.com/ansible/ansible/issues/76030#issuecomment-1137238958
it doesn't seems to be possible to depends on one stand alone role.
We nay need to use [jeff's php collection](https://github.com/geerlingguy/ansible-collection-php_roles) as dependency instead

2023-02-13 17:31 UTC, staticdev commented
@aalaesar I think you will need somehow to rebase to be able to merge since Github says there is a conflict in meta/main.yml

2023-02-13 18:00 UTC, wiktor2200 commented on galaxy.yml
> +dependencies: {}
Hmm... I can see. It's a mess there in Ansible repos and documentation. I guess using whole collection as dependency could be dangerous (or at least decreasing readability).
Adding Jeff's submodule to our `roles` directory is not ideal, but may be one of the solutions.
The other one, could be skip defining `dependencies` now. Then see what will happen later when collection would be released and we will see if role's dependencies are resolved while trying to install with `galaxy install` command.

2023-02-13 19:24 UTC, aalaesar commented on galaxy.yml
> +dependencies: {}
Hmm. I think that, at least, the requirement.yml and dependency  chapter from the role's readme should be moved to the collection root folder and readme.
So there would be a minimal amount of documentation to install completely the collection.

2023-02-13 19:30 UTC, staticdev commented on galaxy.yml
> +dependencies: {}
Strange.. can't we have both link in here?
https://github.com/staticdev/linux-workstation-playbook/blob/main/requirements.yml

2023-02-13 19:35 UTC, wiktor2200 commented on galaxy.yml
> +dependencies: {}
I really like @staticdev's solution :)
I also agree with @aalaesar  that installation of collection should be doable with "minimal" effort with fail-safe default parameters and dependencies.

2023-02-15 08:12 UTC, aalaesar commented on galaxy.yml
> +dependencies: {}
> Strange.. can't we have both link in here? https://github.com/staticdev/linux-workstation-playbook/blob/main/requirements.yml

yes, that the point.
that pretty much all what we can do to help customer install dependencies.
we can't use the "automated way" that uses deps in galaxy.yml

2023-02-15 15:15 UTC, aalaesar commented on galaxy.yml
> +dependencies: {}
I've updated the readme to give instruction about installing standalone roles used by the collection

2023-02-15 22:05 UTC, staticdev commented
Lets go.

2023-02-16 14:30 UTC, aalaesar commented on galaxy.yml
> +dependencies: {}
@wiktor2200 one last review before the big merge ?

2023-02-16 15:24 UTC, wiktor2200 approved these changes
LGTM :)

2023-02-18 00:08 UTC, merged