Add pre-commit update action
aalaesar/install_nextcloud pull request #210
Opened 2023-02-11 19:25 UTC by wiktor2200

Hi @aalaesar  @staticdev! I've added github action for pre-commit update. 
It's based on example from here: https://github.com/browniebroke/pre-commit-autoupdate-action

It requires a token: `token: ${{ secrets.GITHUB_TOKEN }}` for pull request creation, could you help with that?

2023-02-11 20:06 UTC, staticdev requested changes
Thanks @wiktor2200 Just check for annoying lint warnings on gh since they eventually become errors in following lint versions.

About GITHUB_TOKEN it will just work =) other workflows also need it

2023-02-11 20:40 UTC, wiktor2200 commented
Fixed. I've also noticed that I put it in wrong directory, so I moved it to proper one.

2023-02-12 21:19 UTC, aalaesar approved these changes
LGTM

2023-02-13 17:29 UTC, staticdev approved these changes

2023-02-13 17:29 UTC, merged