Adds support for Debian Buster
aalaesar/install_nextcloud pull request #78
Opened 2019-11-18 09:48 UTC by Sprinterfreak

* Add debian-buster to supported os list
* Add php-fpm7.3 environment meta
* Add nginx template client_body_timeout avoids web-updater getting killed by nginx

2019-11-19 20:03 UTC, conorsch commented
@Sprinterfreak Thank you for submitting this! It wasn't quite what I needed in order to get Buster support on my setup. Can you take a look at https://github.com/aalaesar/install_nextcloud/pull/81 and see if that meets your needs, as well?

2022-05-26 14:38 UTC, staticdev commented
@aalaesar this should be closed. #81 already adds it.

2022-05-26 14:39 UTC, staticdev requested changes
@Sprinterfreak please close this PR, it was fixed on #81.

2022-05-26 14:39 UTC, staticdev commented on meta/main.yml
This is already supported.

2022-06-14 06:50 UTC, closed without merging